plugins:
  - jekyll-remote-theme
  
remote_theme: just-the-docs/just-the-docs
repository: OnslowCollege/OnslowCollege.github.io
# theme: just-the-docs
title: Onslow College Digital Technology
repository: OnslowCollege/onslowcollege.github.io
search_enabled: true
nav_sort: case_insensitive
logo: "/assets/images/logo.png"
aux_links:
  "Onslow College":
    - "https://www.onslow.school.nz/"
aux_links_new_tab: true
color_scheme: onslow

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
